id: arduino:cloud_asr
name: Cloud ASR
description: |
  Cloud ASR Brick provides a unified and flexible way to connect cloud-based Automatic Speech Recognition (ASR) services and transform spoken audio into text.
  It enables real-time, streaming transcription from a connected microphone, leveraging leading cloud providers to deliver low-latency speech-to-text processing.
category: audio
mount_devices_into_container: true
required_devices:
  - microphone
requires_container: false
requires_model: false
variables:
  - name: API_KEY
    description: "API Key for the cloud-based Speech to Text service"
  - name: LANGUAGE
    description: "Language code for transcription (e.g., en, it). Default: en"
disabled: true
